stages:
  - builds
  - tests
  - upload

cdsresponder-build:
  image: "docker:19.03.11"
  stage: builds
  services:
    - docker:dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login $DOCKER_REPOSITORY --username "gitlab-ci-token" --password-stdin
  script:
    - cd cdsresponder; docker build . -t $DOCKER_REPOSITORY/cdsresponder:$CI_PIPELINE_IID
    - docker push $DOCKER_REPOSITORY/cdsresponder:$CI_PIPELINE_IID
  tags:
    - gnm
    - docker

cdsreaper-build:
  image: "docker:19.03.11"
  stage: builds
  services:
    - docker:dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login $DOCKER_REPOSITORY --username "gitlab-ci-token" --password-stdin
  script:
    - cd cdsreaper; docker build . -t $DOCKER_REPOSITORY/cdsreaper:$CI_PIPELINE_IID
    - docker push $DOCKER_REPOSITORY/cdsreaper:$CI_PIPELINE_IID
  tags:
    - gnm
    - docker

logviewer-build:
  image: registry.gitlab.com/codmill/customer-projects/guardian/pluto-core/projectlockerbuild:20210302_1
  stage: builds
  variables:
    JAVA_OPTS: -Dsbt.ivy.home=./cdslogviewer/.ivy2 -Divy.home=./cdslogviewer/.ivy2
    SBT_JUNIT_OUTPUT: ./junit-tests
  script:
    - cd cdslogviewer
    - if [ -d ".sbt" ]; then rm -rf ${HOME}/.sbt; mv .sbt ${HOME}; fi
    - if [ ! -d "junit-tests" ]; then mkdir junit-tests; fi
    - sbt test:compile
    - sbt test
    - mv ${HOME}/.sbt .sbt || true
  artifacts:
    reports:
      junit: cdslogviewer/junit-tests/*.xml
  cache:
    key: ${CI_COMMIT_REF_SLUG}-sbt
    paths:
      - cdslogviewer/target/
      - cdslogviewer/.sbt/
      - cdslogviewer/.ivy2/

logfrontend-build:
  image: node:12.18-alpine3.12
  stage: builds
  script:
    # git is required for yarn to be able to checkout the shared components
    - apk add --no-cache git
    - cd cdslogviewer/frontend
    - sh ./setup_headers.sh
    - yarn install
    - yarn lint
    - yarn test
    - yarn build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node
    paths:
      - cdslogviewer/frontend/node_modules
  artifacts:
    paths:
      - cdslogviewer/public/javascripts/bundle.js
    reports:
      junit: cdslogviewer/frontend/junit.xml

cdsresponder-test:
  image: $DOCKER_REPOSITORY/cdsresponder:$CI_PIPELINE_IID
  stage: tests
  script:
    - cd /opt/cdsresponder; python coverage run -m nose --source=$PWD --with-xunit
  artifacts:
    reports:
      junit: /opt/cdsresponder/nosetests.xml
  tags:
    - gnm
    - docker

uploads:
  image: "docker:19.03.11"
  stage: upload
  services:
    - docker:dind
  script:
    - docker pull $DOCKER_REPOSITORY/cdsresponder:$CI_PIPELINE_IID
    - docker tag $DOCKER_REPOSITORY/cdsresponder:$CI_PIPELINE_IID guardianmultimedia/cdsresponder:$CI_PIPELINE_IID
    - docker login -u "${DOCKER_USER}" -p "${DOCKER_PAT}"
    - docker push guardianmultimedia/cdsresponder:$CI_PIPELINE_IID
  tags:
    - gnm
    - docker
